"""Report database layer for PostgreSQL.

Manages report schema initialization, user auth tables, and report aliases.
"""
from typing import Optional
from model.db import connect


def init_db():
    """Call once at app startup (e.g. FastAPI startup event).

    Creates tables with IF NOT EXISTS in PostgreSQL.
    """
    with connect() as conn:
        with conn.cursor() as cursor:
            # Users table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email          VARCHAR(255) NOT NULL,
                    password_hash  VARCHAR(255),
                    google_id      VARCHAR(255),
                    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
                    CONSTRAINT uq_users_email UNIQUE (email),
                    CONSTRAINT uq_users_google UNIQUE (google_id)
                );
            """)
            # Migration for existing databases
            try:
                cursor.execute("ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;")
            except Exception:
                pass

            try:
                cursor.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE;")
            except Exception:
                pass

            try:
                cursor.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_id VARCHAR(50) DEFAULT 'free';")
                cursor.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) DEFAULT 'inactive';")
            except Exception:
                pass

            # Payments table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS payments (
                    payment_id       VARCHAR(255) PRIMARY KEY,
                    user_id          INT,
                    user_email       VARCHAR(255),
                    plan_id          VARCHAR(50) NOT NULL,
                    billing_cycle    VARCHAR(50) NOT NULL,
                    amount_cents     INT NOT NULL,
                    currency         VARCHAR(10) NOT NULL DEFAULT 'usd',
                    status           VARCHAR(50) NOT NULL DEFAULT 'pending',
                    stripe_intent_id VARCHAR(255),
                    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)



            # Report-level table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS reports (
                    report_id                 VARCHAR(255) PRIMARY KEY,
                    owner_user_id             INT NOT NULL,
                    content_hash              VARCHAR(255) NOT NULL,
                    status                    VARCHAR(50) NOT NULL DEFAULT 'pending',
                    total_pages               INT NOT NULL DEFAULT 0,
                    page_matching             TEXT,
                    common_render_dpi         DOUBLE PRECISION,
                    page_size_mismatch        BOOLEAN NOT NULL DEFAULT FALSE,
                    page_size_mismatch_details TEXT,
                    created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uk_owner_content_hash UNIQUE (owner_user_id, content_hash),
                    FOREIGN KEY (owner_user_id) REFERENCES users(user_id) ON DELETE CASCADE
                );
            """)

            # Page-level table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS report_pages (
                    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    report_id                   VARCHAR(255) NOT NULL,
                    page_number                 INT,
                    matched_new_page_number     INT,
                    page_status                 VARCHAR(50) NOT NULL,
                    page_match_method           VARCHAR(50),
                    page_match_score            DOUBLE PRECISION,
                    comparison_mode             VARCHAR(50),
                    redesign_detected           BOOLEAN NOT NULL DEFAULT FALSE,
                    alignment_match_count       INT,
                    alignment_inlier_count      INT,
                    alignment_confidence        DOUBLE PRECISION,
                    alignment_error             TEXT,
                    render_dpi                  DOUBLE PRECISION,
                    page_size_pts_width         DOUBLE PRECISION,
                    page_size_pts_height        DOUBLE PRECISION,
                    page_size_mismatch          BOOLEAN NOT NULL DEFAULT FALSE,
                    page_size_mismatch_details  TEXT,
                    overall_similarity          DOUBLE PRECISION,
                    overall_summary             TEXT,
                    changes                     TEXT NOT NULL,
                    annotated_source_png        BYTEA,
                    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (report_id) REFERENCES reports(report_id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            """)

            # Deduplication aliases
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS report_aliases (
                    alias_id  VARCHAR(255) PRIMARY KEY,
                    report_id VARCHAR(255) NOT NULL,
                    FOREIGN KEY (report_id) REFERENCES reports(report_id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            """)

            # Async job tracking
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS jobs (
                    job_id           VARCHAR(255) PRIMARY KEY,
                    owner_user_id    INT NOT NULL,
                    job_type         VARCHAR(50) NOT NULL,
                    status           VARCHAR(50) NOT NULL DEFAULT 'pending',
                    progress_message TEXT,
                    result_id        VARCHAR(255),
                    was_cached       INT,
                    error_message    TEXT,
                    drawing_id       VARCHAR(255),
                    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (owner_user_id) REFERENCES users(user_id) ON DELETE CASCADE
                );
            """)

            # Human review data
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS change_reviews (
                    review_id     VARCHAR(255) PRIMARY KEY,
                    report_id     VARCHAR(255) NOT NULL,
                    page_number   INT NOT NULL,
                    change_index  INT NOT NULL,
                    status        VARCHAR(50) NOT NULL DEFAULT 'unreviewed',
                    note          TEXT,
                    reviewed_at   TIMESTAMP,
                    reviewer_id   VARCHAR(255),
                    CONSTRAINT uk_report_page_change UNIQUE (report_id, page_number, change_index),
                    FOREIGN KEY (report_id) REFERENCES reports(report_id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            """)
            # Migration: add pipeline_version and total_changes columns for report_pages
            try:
                cursor.execute(
                    "ALTER TABLE report_pages ADD COLUMN IF NOT EXISTS pipeline_version VARCHAR(50) DEFAULT 'legacy';"
                )
                cursor.execute(
                    "ALTER TABLE report_pages ADD COLUMN IF NOT EXISTS total_changes INT DEFAULT 0;"
                )
            except Exception:
                pass  # Columns may already exist on re-runs

            cursor.execute("CREATE INDEX IF NOT EXISTS idx_reports_owner ON reports (owner_user_id)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_reports_status ON reports (status)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_pages_report ON report_pages (report_id)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_jobs_owner ON jobs (owner_user_id)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs (status)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_change_reviews_report ON change_reviews (report_id)")


def resolve_report_id(report_id: str, owner_user_id: Optional[int] = None) -> str:
    """Map a report id to the underlying report id. Alias resolves to real report."""
    with connect() as conn:
        with conn.cursor() as cursor:
            if owner_user_id is not None:
                cursor.execute("""
                    SELECT ra.report_id 
                    FROM report_aliases ra
                    JOIN reports r ON r.report_id = ra.report_id
                    WHERE ra.alias_id = %s AND (r.owner_user_id IS NULL OR r.owner_user_id = %s)
                """, (report_id, owner_user_id))
            else:
                cursor.execute("SELECT report_id FROM report_aliases WHERE alias_id = %s", (report_id,))
            row = cursor.fetchone()
    return row["report_id"] if row else report_id
